export default {
	LOGIN_FAIL: 'Email or password is Incorrect',
	LOGIN: 'Login Successful',
	OTP: 'OTP sent successfully',
	OTP_FAIL: 'Wrong OTP sent',
	OTP_EMAIL_VERIFIED: 'Email verified successfully',
	OTP_MOBILE_VERIFIED: 'Mobile number verified successfully',
	TOKEN_EXPIRED: 'JWT token expired, Login again!',
	UPDATE_MOBILE_NUMBER: 'Mobile Number Updated Successfully',
	UPDATE_EMAIL: 'Email Updated Successfully',
	AUTH_EXIST_FAIL: 'User already exist',
	AUTH_REGISTER_SUCCESS: 'Registrated user successfully',
	AUTH_COMFIRM_PASSWORD_FAIL: 'Mismatch confirm password & password',
	AUTH_CHECK_PASSWORD_FAIL: 'Wrong password entered',
	USER_NOT_FOUND: 'User doesnt exist',
	PASSWORD_RESET: 'Password reset successfully',
	CHANGE_PASSWORD_FAIL: 'Failed to change the password',
	PASSWORD_RESET_MAIL_SENT: 'Reset pasword mail sent successfully',
	CHANGE_PASSWORD_SUCCESS: 'Password updated successfully',
	CHANGE_PASSWORD_MATCH_FAIL: 'Wrong password entered',
	FORGOT_PASSWORD_FAIL: 'Failed to send mail',
	USER_FILER_LIST: 'Filter list',
	USER_PROFILE_UPDATE_SUCCESS: 'Users profile updated successfully',
	USER_PROFILE_UPDATE_FAIL: 'Users profile updated failed',

	USER_DETAILS_SUCCESS: 'Users details fetched successfully',
	USER_CHAT_REQUEST_SUCCESS: 'Chat request sent successfully',
	USER_CHAT_REQUEST_FAIL: 'Failed to send chat request',
	MESSAGE_SENT_SUCCESS: 'Message sent successfully',
	MESSAGE_SENT_FAIL: 'Failed to send message',
	MESSAGE_LIST_SUCCESS: 'Message list fetched successfully',
	MESSAGE_LIST_FAIL: 'Failed to fetch message list',
	MESSAGE_UPDATE_SUCCESS: 'Message status updated successfully',
	MESSAGE_UPDATE_FAIL: 'Failed to update the status',

	CMS_CONTENT_LIST_SUCCESS: 'Fetched the content list successfully',
	CMS_CONTENT_LIST_FAIL: 'Failed to fetch content list',
	CMS_CONTENT_ADD_SUCCESS: 'CMS content created successfully',
	CMS_CONTENT_ADD_FAIL: 'CMS content add failed',
	CMS_CONTENT_UPDATE_FAIL: 'Failed to update cms content',
	CMS_CONTENT_UPDATE_SUCCESS: 'CMS content updated successfully',
	CMS_CONTENT_DELETE_SUCCESS: 'CMS content deleted successfully',
	CMS_CONTENT_DELETE_FAIL: 'CMS content delete  failed',

	CMS_KYC_DOCS_LIST_SUCCESS: 'Fetched KYC Docs list successfully',
	CMS_KYC_DOCS_LIST_FAIL: 'Failed to fetch KYC docs list',
	CMS_KYC_DOCS_ADD_SUCCESS: 'KYC docs created successfully',
	CMS_KYC_DOCS_ADD_FAIL: 'KYC docs created successfully',
	CMS_KYC_DOCS_UPDATE_SUCCESS: 'KYC docs updated successfully',
	CMS_KYC_DOCS_UPDATE_FAIL: 'Failed to update KYC docs',
	CMS_KYC_DOCS_DELETE_SUCCESS: 'KYC docs deleted successfully',
	CMS_KYC_DOCS_DELETE_FAIL: 'Failed to delete KYC docs',

	KYC_REQUEST_SUCCESS: 'KYC requests fetched successfully',
	KYC_REQUEST_FAIL: 'Failed to fetch the KYC requests list',
	KYC_REQUEST_ADD_SUCCESS: 'KYC requests created successfully',
	KYC_REQUEST_ADD_FAIL: 'Failed to add KYC request',
	KYC_REQUEST_VERIFY_SUCCESS: 'KYC doc verfified successfully',
	KYC_REQUEST_VERIFY_FAIL: 'KYC doc verfication failed',
	KYC_REQUEST_UPDATE_SUCCESS: 'KYC doc updated successfully',
	KYC_REQUEST_UPDATE_FAIL: 'Failed to update KYC doc',
	KYC_REQUEST_APPROVE_SUCCESS: 'KYC doc approved successfully',
	KYC_REQUEST_APPROVE_FAIL: 'Failed to approved KYC doc',
	KYC_REQUEST_REJECT_SUCCESS: 'KYC doc rejected successfully',
	KYC_REQUEST_REJECT_FAIL: 'Failed to reject KYC doc',
	KYC_REQUEST_NOT_EXIST: 'KYC request does not exist',
	KYC_REQUEST_APPROVED: 'KYC request already approved',
	KYC_REQUEST_REJECTED: 'KYC request already rejected',

	SUPPORT_REQUEST_ADD_SUCCESS: 'Support request added successfully',
	SUPPORT_REQUEST_ADD_FAIL: 'Failed to add support request',
	SUPPORT_REQUEST_GET_SUCCESS: 'Support request list fetched successfully',
	SUPPORT_REQUEST_GET_FAIL: 'Failed to fetch support request list',
	SUPPORT_REQUEST_UPDATE_SUCCESS: 'Support request updated successfully',
	SUPPORT_REQUEST_UPDATE_FAIL: 'Failed to update support request',
	SUPPORT_REQUEST_DELETE_SUCCESS: 'Support request deleted successfully',
	SUPPORT_REQUEST_DELETE_FAIL: 'Failed to delete support request successfully',
	SUPPORT_REQUEST_SINGLE_SUCCESS:
		'Support request detials fetched successfully',
	SUPPORT_REQUEST_SINGLE_FAIL: 'Failed to fetch support request detail',

	NOTIFICATION_LIST_SUCCESS: 'Notification list fetched successfully',
	NOTIFICATION_LIST_FAIL: 'Failed to fetch notfication list',

	CMS_FAQ_NOT_EXIST: 'FAQ does not exist',
	CMS_FAQ_LIST_SUCCESS: 'Fetched FAQs list successfully',
	CMS_FAQ_LIST_FAIL: 'Failed to fetch FAQs list',
	CMS_FAQ_ADD_SUCCESS: 'FAQ created successfully',
	CMS_FAQ_ADD_FAIL: 'Failed to add FAQ',
	CMS_FAQ_GET_SUCCESS: 'Fetched FAQ detials successfully',
	CMS_FAQ_GET_FAIL: 'Failed to get faq detials',
	CMS_FAQ_UPDATE_SUCCESS: 'FAQ updated successfully',
	CMS_FAQ_UPDATE_FAIL: 'Failed to update FAQ',
	CMS_FAQ_DELETE_SUCCESS: 'FAQ deleted successfully',
	CMS_FQA_DELETE_FAIL: 'Failed to delete FAQ',
	CMS_BLOGS_LIST_SUCCESS: 'Fetched updates list successfully',
	CMS_BLOGS_LIST_FAIL: 'Failed to fetch updates list',
	CMS_BLOGS_ADD_SUCCESS: 'Updates created successfully',
	CMS_BLOGS_ADD_FAIL: 'Failed to add updates',
	CMS_BLOGS_UPDATE_SUCCESS: 'Updates updated successfully',
	CMS_BLOGS_UPDATE_FAIL: 'Failed to update updates',
	CMS_BLOGS_DELETE_SUCCESS: 'Updates deleted successfully',
	CMS_BLOGS_DELETE_FAIL: 'Failed to delete updates',
	CMS_BLOGS_IMG_UPDATE_SUCCESS: 'Updates image uploaded successfully',
	CMS_BLOGS_IMG_UPDATE_FAIL: 'Failed to upload updates image',

	CREATED_COLLECTION_GET_SUCCESS: 'Fetched created collection successfully',
	CREATED_COLLECTION_GET_FAIL: 'Failed to fetch the created collection',
	CREATED_COLLECTION_ADD_SUCCESS: 'Collection created successfully',
	CREATED_COLLECTION_ADD_FAIL: 'Failed to create collection',
	CREATED_COLLECTION_UPDATE_SUCCESS: 'Collection updated successfully',
	CREATED_COLLECTION_UPDATE_FAIL: 'Failed to update collection',
	CREATED_COLLECTION_DELETE_SUCCESS: 'Collection deleted successfully',
	CREATED_COLLECTION_DELETE_FAIL: 'Failed to delete collection',

	CREATED_ART_NFT_EXIST: 'Art NFT already exist',
	CREATED_ART_NFT_FAIL: 'Failed to create Art NFT',
	CREATED_ART_NFT_SUCCESS: 'Art NFT created successfully',
	ART_NFT_LIST_SUCCESS: 'Art NFT list fetched successfully',
	ART_NFT_LIST_FAIL: 'Failed to fetch Art NFt',
	ART_NFT_DETAILS_SUCCESS: 'Arts NFT details fetched successfully',
	ART_NFT_DETAILS_FAIL: 'Failed to fetch Art NFT detials',
	ART_NFT_UPDATE_SUCCESS: 'Art NFT status updated successfully',
	ART_NFT_UPDATE_FAIL: 'Failed to update the status of Art NFT',
	ART_NFT_BLOCK_SUCCESS: 'Art NFT blocked successfully',
	ART_NFT_BLOCK_FAIL: 'Failed to block art NFT',
	ART_NOT_FOUND: 'Art NFT not found',
	PROMOTE_SUCCESS: 'Promotion success successfully',
	PROMOTE_FAILED: 'Promtion failed',

	USER_ART_NFT_LIST_SUCCESS: 'User onsale art NFT list fetched successfully',
	AUCTION_IS_IN_PROGRESS:
		'You cannot update your NFT as Auction is in progress',
	USER_LIST_SUCCESS: 'Users list fetched successfully',
	USER_LIST_FAIL: 'Failed to fetch user list',

	FOLLOW_SUCCESS: 'Follow Success',
	FOLLOW_FAILED: 'Follow Failed',
	UNFOLLOW_SUCCESS: 'Unfollow Success',
	UNFOLLOW_FAILED: 'Unfollow Failed',
	COLLECTIBLE_LIST_SUCCESS: 'Collectible list fetched successfully',
	COLLECTIBLE_LIST_FAILED: 'Failed to fetch Collectible list',
	TRADING_HISTORY_LIST: 'Trading history fetched successfully',
	BID_LIST: 'bidding history fetched successfully',
	PAYMENT_LIST_SUCCESS: 'payment history list fetched successfully',
	PAYMENT_LIST_FAIL: 'Failed to fetch paymetent hisotry list',

	CREATED_ONSALE_ART_NFT_FAIL: 'Failed to create onsale Art NFT',
	CREATED_ONSALE_ART_NFT_SUCCESS: 'Onsale Art NFT created successfully',
	ONSALE_UPDATE_SUCCESS: 'NFT on sale updated successfully',
	ONSALE_DELETED: 'NFT on sale deleted',
	ART_ALREADY_SOLD: 'Art on sale already sold',

	NEWS_ADD_SUCCESS: 'News added successfully',
	NEWS_ADD_FAIL: 'Failed to add news',
	NEWS_GET_SUCCESS: 'Fetched news successfully',
	NEWS_GET_FAIL: 'Failed to fetch news',
	NEWS_UPDATE_SUCCESS: 'News updated successfully',
	NEWS_UPDATE_FAIL: 'Failed to update news',
	NEWS_DELETE_SUCCESS: 'News deleted successfully',
	NEWS_DELETE_FAIL: 'Failed to delete news',

	PAYMENT_METHOD_NOT_EXIST: 'Payment method does not exist',
	PAYMENT_METHOD_ADD_SUCCESS: 'Payment method added successfully',
	PAYMENT_METHOD_ADD_FAIL: 'Failed to add payment method',
	PAYMENT_METHOD_UPDATE_SUCCESS: 'Payment method updated successfully',
	PAYMENT_METHOD_UPDATE_FAIL: 'Failed to update payment method',
	PAYMENT_METHOD_DELETE_SUCCESS: 'Payment method removed successfully',
	PAYMENT_METHOD_DELETE_FAIL: 'Failed to remove payment method',

	ACHIEVEMENT_ADD_SUCCESS: 'Achievement added successfully',
	ACHIEVEMENT_ADD_FAIL: 'Failed to add achievement',
	ACHIEVEMENT_GET_SUCCESS: 'Fetched achievement successfully',
	ACHIEVEMENT_GET_FAIL: 'Failed to fetch achievement',
	ACHIEVEMENT_UPDATE_SUCCESS: 'Achievement updated successfully',
	ACHIEVEMENT_UPDATE_FAIL: 'Failed to update achievement',
	ACHIEVEMENT_DELETE_SUCCESS: 'Achievement deleted successfully',
	ACHIEVEMENT_DELETE_FAIL: 'Failed to delete achievement',

	//Admin
	USER_GET_SUCCESS: 'User detials fetched successfully',
	USER_GET_FAIL: 'Failed to fetch single user',
	COLLECTOR_LIST_SUCCESS: 'Collectors list fetched successfully',
	COLLECTOR_LIST_FAIL: 'Failed to fetch lsit',
	COLLECTOR_BLOCK_SUCCESS: 'Collector blocked successfully',
	COLLECTOR_BLOCK_FAIL: 'Failed to block collector',

	ARTIST_LIST_SUCCESS: 'Artist list fetched successfully',
	ARTIST_LIST_FAIL: 'Failed to fetch artist list',
	ARTIST_BLOCK_SUCCESS: 'Artist blocked successfully',
	ARTIST_BLOCK_FAIL: 'Failed to block artist',
	ARTIST_UNBLOCK_SUCCESS: 'Artist unblocked successfully',
	ARTIST_UNBLOCK_FAIL: 'Failed to unblock artist',

	GALLERY_LIST_SUCCESS: 'Gallery list fetched successfully',
	GALLERY_LIST_FAIL: 'Failed to fetch gallery list',
	GALLERY_BLOCK_SUCCESS: 'Gallery blocked successfully',
	GALLERY_BLOCK_FAIL: 'Failed to block gallery',
	GALLERY_UNBLOCK_SUCCESS: 'Gallery unblocked successfully',
	GALLERY_UNBLOCK_FAIL: 'Failed to unblock gallery',

	ARTFAIR_LIST_SUCCESS: 'Art fair list fetched successfully',
	ARTFAIR_LIST_FAIL: 'Failed to fetch art fair list',
	ARTFAIR_BLOCK_SUCCESS: 'Artfair blocked successfully',
	ARTFAIR_BLOCK_FAIL: 'Failed to block artfair',
	ARTFAIR_UNBLOCK_SUCCESS: 'Artfair unblocked successfully',
	ARTFAIR_UNBLOCK_FAIL: 'Failed to unblock artfair',

	REPORT_GENERATE_SUCCESS: 'Report generated successfully',
	REPORT_GENERATE_FAIL: 'Failed to generate report',
	REPORT_ANALYTICS_GET_SUCCESS: 'Report analytics feched successfully',
	REPORT_ANALYTICS_GET_FAIL: 'Failed to fetch report analytics',

	NOTIFICATION_ADD_SUCCESS: 'Notification added successfully',
	NOTIFICATION_ADD_FAIL: 'Notification added successfully',
	NOTIFICATION_READ_SUCCESS: 'Notification read successfully',
	NOTIFICATION_READ_FAIL: 'Failed to update read notification',

	HEADER_CONTENT_LIST_SUCCESS: 'Headers content added successfully',
	HEADER_CONTENT_LIST_FAIL: 'Failed to add headers content',
	HEADER_CONTENT_UPDATE_SUCCESS: 'Headers content updated successfully',
	HEADER_CONTENT_UPDATE_FAIL: 'Failed to update headers content',
	HEADER_CONTENT_DELETE_SUCCESS: 'Headers content deleted successfully',
	HEADER_CONTENT_DELETE_FAIL: 'Failed to delete headers content',
	HEADER_CONTENT_IMAGE_UPLOAD_SUCCESS: 'Headers image uploaded successfully',
	HEADER_CONTENT_IMAGE_UPLOAD_FAIL: 'Failed to upload image for headers',

	USER_EMAIL_UPDATE_SUCCESS: 'User email updated successfully',
	USER_EMAIL_UPDATE_FAIL: 'Failed to update user email',

	PURCHASED_LIST_SUCCESS: 'Purchased list fetched successfully',
	PURCHASED_LIST_FAIL: 'Failed to fetch purchased list',
	ONSALE_LIST_SUCCESS: 'Onsale list fetched successfully',
	ONSALE_LIST_FAIL: 'Failed to fetch onsale list',
	SOLD_LIST_SUCCESS: 'Sold list fetched successfully',
	SOLD_LIST_FAIL: 'Failed to fetch sold list',

	DASHABOARD_COUNT_SUCCESS: 'Dashboard count fetched successfully',
	DASHABOARD_COUNT_FAIL: 'Failed to fetch dashboard count',

	REFERRAL_ADD_SUCCESS: 'Referral added successfully',
	REFERRAL_ADD_FAIL: 'Referral added failed',
	REFERRAL_ACTIVATED: 'Referral activated',
	REFERRAL_DEACTIVATED: 'Referral de-activated',
	REFERRAL_LIST: 'Referral list fetched',
	REFERRAL_LIST_FAILED: 'Referral list not found',

	BUY_SELL_LIST_SUCCESS: 'Buy & sell list fetched successfully',
	BUY_SELL_LIST_FAIL: 'Failed to fetch buy & sell list',
	BUY_SELL_GET_SUCCESS: 'Buy & sell detial fetched successfully',
	BUY_SELL_GET_FAIL: 'Failed to fetch buy & sell detail',

	SALE_IS_ON_AUCTION: 'This art is on timed auction.',
	ONLY_FIAT_ACCEPT: 'This art only accept fiat payment',
	PLAN_NOT_FOUND: 'plan not found',
	TITLE_ALREADY_EXIST: 'Art with this title already exist',
};
